server:
  port: 8082
  servlet:
    context-path: /api

spring:
  application:
    name: el-aparato-service
  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true
    database:
      platform: org.hibernate.dialect.MySQLDialect
    defer-datasource-initialization: true
  sql:
    init:
      mode: always
      platform: mysql
      continue-on-error: true
      data-locations: classpath:db/insert_data.sql
      includes:
        message: always
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: ${DB_HOST}/elaparato?createDatabaseIfNotExist=true
    username: ${DB_USER}
    password: ${DB_PASSWORD}

  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8080/realms/el-aparato-mascheroni

logging:
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} [%highlight(%level)] [%cyan(%thread)] %green(%logger{15}) - %msg%n"
  level:
    org:
      springframework:
        web: INFO
    hibernate: ERROR