server:
    port: 9090

spring:
    cloud:
        gateway:
            default-filters:
            - TokenRelay
            routes:
                - id: keycloak-admin-users
                  predicates:
                      - Path=/users/**
                  uri: http://localhost:8181
                - id: el-aparato-service
                  predicates:
                      - Path=/api/**
                  uri: http://localhost:8082



    security:
        oauth2:
            client:
                provider:
                    keycloak-el-aparato:
                        issuer-uri: http://localhost:8080/realms/el-aparato-mascheroni
                registration:
                    keycloak-el-aparato:
                        authorization-grant-type: authorization_code
                        client-id: gateway-client
                        client-secret: AbPsqVb7sMrUuyWbubdNDeiWDNylfPmF
                        redirect-uri: http://localhost:9090/login/oauth2/code/keycloak
                        scope:
                            - openid
